### ISSUE TITLE
Is this repo abandoned?

### ISSUE THREAD

**Issue by zdraganov** [99designs/gqlgen-contrib#30]
I am seeing that there's no progress on this repo last year. Are there any contributors that can merge PRs?
We are struggling with version inconsistency and old dependencies.

**Comment by StevenACoffman** [comment]
@mathewbyrne @mtibben @lwc @MichaelJCompton Can you make me a contributor to this repo so I can spruce it up a bit? Thanks!

**Comment by mtibben** [comment]
Done!

**Comment by StevenACoffman** [comment]
@mtibben I'm still not able to merge PRs here. Maybe I need a different access?

**Comment by mtibben** [comment]
check your email for the invite

**Comment by StevenACoffman** [comment]
Ah! Thanks! I have two email accounts associated, and I checked the wrong one! Thanks!

**Comment by StevenACoffman** [comment]
Ok, not really abandoned anymore!
